name: Lint

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: lint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: kairos-io/kairos/.github/workflows/reusable-linting.yaml@d17464a24dd6eaba061042adff9fb29aa8236c5c  # v4.3.0
    with:
      yamldirs: "."
